name: Create Release on Push

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Generate a version number (e.g., timestamp-based)
      - name: Generate version
        id: version
        run: echo "version=$(date +%Y%m%d%H%M%S)" >> $GITHUB_OUTPUT

      # Create a ZIP file of the apitemplates/ folder
      - name: Create ZIP
        run: |
          if [ -d "apitemplates" ]; then
            zip -r apitemplates.zip apitemplates/
          else
            echo "apitemplates/ directory not found, creating empty zip"
            touch empty.txt
            zip apitemplates.zip empty.txt
          fi

      # Create a new release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.version.outputs.version }}
          release_name: Release v${{ steps.version.outputs.version }}
          draft: false
          prerelease: false

      # Upload the ZIP file as a release asset
      - name: Upload ZIP to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: apitemplates.zip
          asset_name: apitemplates.zip
          asset_content_type: application/zip